name: forest-fire-risk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - xarray
  - zarr>=2.18,<3
  - dask
  - scikit-learn
  - matplotlib
  - pytest
  - pip:
      - earthengine-api
      - torch
      - torchvision
